AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
